### Write a function so that the columns of the output matrix are powers of the input vector. 
 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
 
 
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 
 


In [1]:
import pandas as pd
import numpy as np

In [2]:
def vander_matrix(ipvector): 
    print("the input vector is",ipvector)
    print('-'*40 ,'\n')
    print("no. of columns in op is N=",len(ipvector),)
    op=np.vander(ipvector,len(ipvector),increasing=False)
    print('\n The output array is \n',op)

In [3]:
vander_matrix([1,2,3,4,5])

the input vector is [1, 2, 3, 4, 5]
---------------------------------------- 

no. of columns in op is N= 5

 The output array is 
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


### Problem Statement 2:  Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
 
The moving average sequence has n-k+1 elements as shown below. 
 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
 
i 1  2  3  4  5  6  7  8  9 10  ===== == == == == == == == == == ==  Input 10 20 30 40 50 60 70 80 90 100  y1      25 = (10+20+30+40)/4  y2      35 = (20+30+40+50)/4  y3      45 = (30+40+50+60)/4  y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4 
 
 
Thus, the moving average sequence has n-k+1=10-4+1=7 values. 



Question: Write a function to find moving average in an array over a window:          Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 
 
 
 
Note: Solution submitted via github must contain all the detailed steps. 
 
 


In [125]:
##n=13 elements sequence ,k=3 
## op elements=13-3+1=11
m=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def mov_avg(m,k):
    print("no. of elememnts in given sequence or list is",len(m),
          '\n\n value of window (used to calculate moving average) is',k,
          '\n\n no. of elements in output sequence is',len(m)-k+1)
    seq=[]
    n=0
    for i in m:
        op_avg=sum(m[n:n+k])/k  ## adding k elements for every iteration and dividing sum by k 
        p=seq.append(op_avg)    ## storing the calcluted average value       
        n=n+1
        q=np.array(seq)
        if n+k>len(m):
            break
    print('\n\nThe output sequence of moving averages is\n\n' ,q)


In [126]:
mov_avg(m,3)

no. of elememnts in given sequence or list is 13 

 value of window (used to calculate moving average) is 3 

 no. of elements in output sequence is 11


The output sequence of moving averages is

 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
